// solid-todo-app/src/App.jsx
import { createSignal, onMount  } from "solid-js";

function App() {

  const [todos, setTodos] = createSignal([]);
  let todoText;

  onMount(() => {
    const existingTodos = localStorage.getItem('todos');
    setTodos(existingTodos ? JSON.parse(existingTodos) : []);
  });

  function addTodo(event) {
    event.preventDefault();
    const next = [...todos(), todoText.value];
    setTodos(next);
    localStorage.setItem('todos', JSON.stringify(next));
  }

  function resetTodo() {
    localStorage.clear();
    const existingTodos = localStorage.getItem('todos');
    setTodos(existingTodos ? JSON.parse(existingTodos) : []);
  }

  return (
    <div>

      <form onSubmit={addTodo}>
        <input type="text" ref={todoText} placeholder="Add a new Task to do"/>
        <input type="submit" value="Add Todo" />
      </form>

      <button onClick={resetTodo}>Reset The To Do List</button>

      <ul>
        {todos().map(todo => (<li key={todo}>{todo}</li>))}  
      </ul>
    </div>
  );
}

export default App;

// svelte-todo-app/src/App.svelte
<script>
	import { onMount } from 'svelte';

	let todos = [];
	let todoText = '';

	onMount(() => {
		const existingTodos = localStorage.getItem('todos');
    	todos = JSON.parse(existingTodos) || [];
	});

	function addTodo() {
		todos = [...todos, todoText];
    	localStorage.setItem('todos', JSON.stringify(todos));
	}

	function resetTodo() {
    	localStorage.clear();
		const existingTodos = localStorage.getItem('todos');
    	todos = JSON.parse(existingTodos) || [];
	}

</script>

<main>

	<form on:submit|preventDefault={addTodo}>
	
		<input bind:value={todoText} placeholder="Add a new Task to do">
		<input type="submit" value="Add todo">
	</form>

	<button on:click={resetTodo}>Reset The To Do List</button>

	<ul>
		{#each todos as todo}
			<li>{todo}</li>
		{/each}
	</ul>


</main>
